### ISSUE TITLE
Issue Running Telepresence on macOS High Sierra

### ISSUE THREAD

**Issue by rymcol** [datawire/telepresence#305]
### What were you trying to do?

run `telepresence`

### What did you expect to happen?

I expect to have my Mac act as if it were in the cluster

### What happened instead?

It failed and asked me to file this report 

### Automatically included information

Command line: `['/usr/local/bin/telepresence']`
Version: `0.67`
Python version: `3.6.2 (default, Sep 27 2017, 10:06:46) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]`
kubectl version: `Client Version: v1.7.3`
oc version: `(error: [Errno 2] No such file or directory: 'oc')`
OS: `Darwin Ryans-MacBook-Pro.local 17.2.0 Darwin Kernel Version 17.2.0: Mon Sep 18 15:44:59 PDT 2017; root:xnu-4570.20.55~19/RELEASE_X86_64 x86_64`
Traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/telepresence", line 257, in call_f
    return f(*args, **kwargs)
  File "/usr/local/bin/telepresence", line 2350, in go
    runner, args
  File "/usr/local/bin/telepresence", line 1513, in start_proxy
    run_id=run_id,
  File "/usr/local/bin/telepresence", line 891, in get_remote_info
    wait_for_pod(runner, remote_info)
  File "/usr/local/bin/telepresence", line 1043, in wait_for_pod
    "Pod isn't starting or can't be found: {}".format(pod["status"])
RuntimeError: Pod isn't starting or can't be found: {'conditions': [{'lastProbeTime': None, 'lastTransitionTime': '2017-09-28T19:10:38Z', 'message': 'No nodes are available that match all of the following predicates:: Insufficient cpu (3).', 'reason': 'Unschedulable', 'status': 'False', 'type': 'PodScheduled'}], 'phase': 'Pending', 'qosClass': 'Burstable'}

```

Logs:

```
emily-162213_europe-west3-c_moonshot-staging-europe-west3-1', '--namespace', 'default', 'get', 'pod', 'telepresence-1506625830-916695-18095-188569391-vz3z3', '-o', 'json'],)...
 125.0 TL | [132] captured.
 125.3 TL | [133] Capturing: (['kubectl', '--context', 'gke_emily-162213_europe-west3-c_moonshot-staging-europe-west3-1', '--namespace', 'default', 'get', 'pod', 'telepresence-1506625830-916695-18095-188569391-vz3z3', '-o', 'json'],)...
 126.0 TL | [133] captured.
 126.2 TL | [134] Capturing: (['kubectl', '--context', 'gke_emily-162213_europe-west3-c_moonshot-staging-europe-west3-1', '--namespace', 'default', 'get', 'pod', 'telepresence-1506625830-916695-18095-188569391-vz3z3', '-o', 'json'],)...
 126.9 TL | [134] captured.
 127.2 TL | [135] Capturing: (['kubectl', '--context', 'gke_emily-162213_europe-west3-c_moonshot-staging-europe-west3-1', '--namespace', 'default', 'get', 'pod', 'telepresence-1506625830-916695-18095-188569391-vz3z3', '-o', 'json'],)...
 127.8 TL | [135] captured.

```

**Comment by ark3** [comment]
Thanks for the bug report. The crash message indicates that Telepresence's proxy pod failed to start due to insufficient CPU resources. This may be because there are no CPU limits set on the proxy pod (for the moment -- see issue #287). 

We haven't tried Telepresence on High Sierra yet. Can you try running Telepresence against the same cluster from another machine, not running High Sierra? My guess is that you will see a similar failure. 

You can also try running Telepresence against an empty cluster, e.g., using [Kubernaut](https://github.com/datawire/kubernaut#quick-start), on your High SIerra machine. If that attempt fails in this manner, then I will need your telepresence.log file to diagnose the problem.

**Comment by rymcol** [comment]
It's almost certainly the CPU
