### ISSUE TITLE
Better distribution mechanism

### ISSUE THREAD

**Issue by itamarst** [datawire/telepresence#45]
Right now we have file you download.

Some issues:

1. We don't notice new versions exist.
2. No update mechanism.
3. No way to use 3rd party Python libraries.

Options (non-exclusive), each of which might cover different subset of the above:

* Native packages (brew, deb, rpm)
* arx/nix-bundle/appimage/PyInstaller
* pex
* Rewrite in Go

Native packages seem best. Some thoughts on tooling:

* For Homebrew just make a brew/cask/tap whatever it's called. It's not hard. Maybe copy Flocker's (reverse patch of https://github.com/ClusterHQ/flocker/pull/2755/files includes most of it I think?).
* `fpm` makes building deb/rpm packages nice.
* https://github.com/alanfranz/fpm-within-docker wraps `fpm` in OS-specific docker images to build per-distro packages.
* https://github.com/krobertson/deb-s3 can make apt repo on s3.
* Probably something equally reasonable can be found for RPMs.
* https://kevinlaw.info/blog/distributing-flask-as-a-package.html explains how to combine Travis-CI and Bintray.

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

There are quite some Python-based AppImages, too. They bundle Python, and AppRun sets `$PYTHONHOME` to point to the Python inside the AppImage, so that the Python application is fully self-contained.

**Comment by itamarst** [comment]
@probonopd thanks for the info! I recommended AppImage to someone else recently, but in the end decided it's not suitable for our particular use case.
