### ISSUE TITLE
Option to parse existing Deployment object to generate the one for telepresence

### ISSUE THREAD

**Issue by itamarst** [datawire/telepresence#9]
Given an existing `Deployment` it should be possible to extract environment variables and the like for the Telepresence `Deployment`.

**Comment by itamarst** [comment]
Jean-Paul expressed a preference for doing this on level of config files, rather than talking to Kubernetes cluster, since it gives more visibility over how things are done.

**Comment by exarkun** [comment]
An idea in the opposite direction might be to have telepresence actually edit the existing Deployment for the user.  A command line:

```
$ telepresence --deployment foo --container bar --new-shell
```

could patch `foo` so that its `bar` container uses the telepresence image and then start a shell in the proxied environment for that container.  When the shell exits, telepresence could even roll the deployment _back_.

That seems kinda snazzy to me though it may be sufficiently automagical that there are some unwanted obscure corner-cases or side-effects.

**Comment by itamarst** [comment]
Current plan:

```
$ telepresence --swap-deployment existingservice --run-shell
```

This swaps out Telepresence proxy for existing pod, and reverts on shutdown.

**Comment by itamarst** [comment]
Remaining work for `swap-deployment` branch:

* Get all tests passing (hopefully just dealing with fiddly bits in `Runner.check_call`).
* Test against OpenShift, make sure it works.
* Make sure no k8s resources are leaked by telepresence or the test suite.
* Update documentation and asciinema video (that could be done in separate branch, though.)
